<a href="https://colab.research.google.com/github/howanu/gc-colab/blob/main/gc_sieve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Formulation

This formulation uses generated vectors  

Define $\textbf{C}(i)$ as the vector generated by setting $1$ at $ji$, i.e.

$$
  {C_j}(i) =
    \begin{cases}
      1 & j\in[2i,3i,\ldots]\\
      0 & \text{otherwise}
    \end{cases} 
$$

For example, $\textbf{C}(3)$ is shown below.

$$
\begin{matrix}
j & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
{C_j}(3) & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 1 & 0
\end{matrix}
$$

Define $\textbf{C'}(i)$ as $\textbf{C}$ flipped at N, i.e.

$$
  {C_j'}(i) = {C_{2N-j}}(i)\text{ where }j\in[0,N]
$$

or using $\omega \equiv 2N \pmod i$,

$$
  {C_j'}(i,N) =
    \begin{cases}
      1 & j \in [\omega, \, \omega + i, \, \omega + 2i, \, \ldots] & j \le N\\
      0 & \text{otherwise} &
    \end{cases} 
$$

For example, $\textbf{C'}(3,5)$ is shown below.

$$
\begin{matrix}
j & 0 & 1 & 2 & 3 & 4 & 5 \\
{C_j}(3) & 0 & 0 & 0 & 0 & 0 & 0 & \color{blue} 1 & 0 & 0 & \color{red} 1 & 0 \\
{C_j'}(3,5) & 0 & \color{red} 1 & 0 & 0 & \color{blue} 1 & 0
\end{matrix}
$$

Define $\textbf{S}$ as 
$$
{S_j}(N) = \sum_{i=2}^{N}{C_j(i) + {C_j'(i,N)}}
$$

For example, $\textbf{S}(5)$ is shown below.

$$
\begin{matrix}
j & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
{C_j}(2) & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
{C_j'}(2,5) & 1 & 0 & 1 & 0 & 1 & 0 \\
{C_j}(3) & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 \\
{C_j'}(3,5) & 0 & 1 & 0 & 0 & 1 & 0 \\
{C_j}(4) & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\
{C_j'}(4,5) & 0 & 0 & 1 & 0 & 0 & 0 \\
{C_j}(5) & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
{C_j'}(5,5) & 1 & 0 & 0 & 0 & 0 & 0 \\
{S_j}(5)  &   &   & 2 & 0 & 3 & 0  \\
\end{matrix}
$$

Then for $N>2$ the formulation is 
$$
\prod_{i=2}^N {S_j}(N) = 0 \,\,\forall N
$$

In [1]:
import numpy as np
import pandas as pd

# {C_j}(i)

In [15]:
def c_fn(i, length=100):
  c = np.zeros(length)
  ones_indices = i*np.arange(2,(length+1)//i)
  #print(ones_indices)
  c[ones_indices] = 1
  return c

c_fn(2, 18+1)

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1.])

In [18]:
c_fn(2,10+1)

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1.])

In [22]:
def c_prime_fn(i, n):
    c = np.zeros(n)
    print(1+(n+1)//i,(2*n+1)//i)
    ones_indices = np.arange((2*n+1)//i,1+(n+1)//i,-1)
    return ones_indices
c_prime_fn(2,10)

6 10


array([10,  9,  8,  7])